<?php

namespace LetmepayIo\Tests\Unit\HttpResources\Requests;

use LetmepayIo\Sdk\Exceptions\Error;
use LetmepayIo\Sdk\HttpResources\Requests\GetPaymentDetailsRequest;
use LetmepayIo\Sdk\HttpResources\Responses\PaymentResponse;
use PHPUnit\Framework\TestCase;

class GetPaymentDetailsRequestTest extends TestCase
{
    private GetPaymentDetailsRequest $request;
    protected function setUp(): void
    {
        $this->request = new GetPaymentDetailsRequest();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     * @covers \LetmepayIo\Sdk\HttpResources\Requests\GetPaymentDetailsRequest
     */
    public function testStaticProperties() : void
    {
        $this->assertEquals('GET', $this->request->method());
        $this->assertEquals(PaymentResponse::class, $this->request->responseClass());
        $this->assertFalse($this->request->isAuth());
        $this->assertNull($this->request->body());
    }

    /**
     * @return void
     * @covers \LetmepayIo\Sdk\HttpResources\Requests\GetPaymentDetailsRequest
     */
    public function testPathWithoutId() : void
    {
        $this->expectException(Error::class);
        $this->expectExceptionMessage('The id parameter is required.');
        $this->request->path();
    }

    /**
     * @return void
     * @covers \LetmepayIo\Sdk\HttpResources\Requests\GetPaymentDetailsRequest
     */
    public function testPath() : void
    {
        $this->request->setId('test');
        $this->assertEquals('/v1/payments/test', $this->request->path());
    }
}